### ISSUE TITLE
avoid transposing arrays in vector fields

### ISSUE THREAD

**Issue by vkrajnak** [broncio123/lds#15]

**Comment by broncio123** [comment]
Can you provide an example of where this has been done?

**Comment by vkrajnak** [comment]
https://github.com/broncio123/lds/blob/b8b59619b417ef8ba437a263a6493061ddeaa414/pylds/vector_fields.py#L32-L35

I'll try to find a way around

**Comment by vkrajnak** [comment]
solve_ivp accepts matrices

**Comment by broncio123** [comment]
> https://github.com/broncio123/lds/blob/b8b59619b417ef8ba437a263a6493061ddeaa414/pylds/vector_fields.py#L32-L35
> 
> I'll try to find a way around, it makes the code hard to read

Hi @vkrajnak  and @VikJGG 

To improve readability _line breaks_ can be implemented, as suggested in PEP8 guidelines, [here](https://pep8.org/#break-before-or-after-binary-operator)

So, the above code can be rewritten as

```
 v = np.array([
               omega * y, 
            - omega * x
                     ]).T 
```

Although not mentioned in PEP8, an alternative approach might be defining array entries as variables, combined an explicit transposition operator, for instance

```
v_x = omega * y
v_y = - omega * x
v =  np.transpose( np.array([v_x, v_y]) )
```
What do you think?

As for matrix notation, I haven't employed ir myself much, but if that improves readability we can discuss it.
Mad love,
b

**Comment by broncio123** [comment]
> solve_ivp accepts matrices

Raise separate issue, please.

**Comment by vkrajnak** [comment]
On the contrary, this is the perfect solution to the issue

**Comment by vkrajnak** [comment]
The function `check_arguments` called in the class `OdeSolver` requires arguments to be 1-dimensional. Making it work would require digging deep into the integration routine. For now, doing away with some of the transposing will have to do.

**Comment by vkrajnak** [comment]
Pull request #28
