### ISSUE TITLE
two vector fields called in compute_lagrangian_descriptor

### ISSUE THREAD

**Issue by vkrajnak** [broncio123/lds#2]
Two vector fields called in compute_lagrangian_descriptor: a global function vector_field_flat and a variable passed as an argument vector_field. The latter does not seem to enter the integration routine, since solve_ivp only accepts one. Is it possible I misunderstand the code?

**Comment by vkrajnak** [comment]
The way vector the two fields are passed to solve_ivp causes issues on earlier versions of scipy (works well on 1.4.1). Can be solved using _partial_ from _functools_ or lambda when defining _f_ in compute_lagrangian_descriptor

**Comment by vkrajnak** [comment]
@broncio123 issue resolved in my pull request.

**Comment by broncio123** [comment]
I will close the issue for now, but I will get back to this later and create a new issue regarding the enhancement in the implementation that you proposed.
