### ISSUE TITLE
parameter issue

### ISSUE THREAD

**Issue by vkrajnak** [broncio123/lds#7]
Used defined parameters used in various functions are defined ad-hoc throughout the code or passed in the background as global variables. The code will be much easier to read if these parameters are defined in one place and passed as arguments.

e.g. _omega_ in HamCenter1D,
_lambda_ in HamSaddle1D,
_flag_pert_ in HamDuffing1D (the code crashes for _flag_pert_ values other than 1 and 2),
_perturbation_params_ in HamDuffing1D

**Comment by broncio123** [comment]
Yeah, I agree. At the moment, these are hard-coded or either taken from global variables.
In future versions of the modular version of the code, we will definitely consider these enhancements. 

Thanks  @vkrajnak
